### ISSUE TITLE
Add gradle to container

### ISSUE THREAD

**Issue by moti0375** [react-native-community/docker-android#186]
Hi,

Is it possible to add gradle installation to the container?
or if gradle exists where it's directory?

I am using this container to build cordova android app in bitbucket pipeline, during the build it fails because it can't find gradle home directory. 

I was able to install gradle in the pipeline using brew but I wonder if it can be pre-installed in the image?

Regards,
Moti.

**Comment by cortinico** [comment]
> Is it possible to add gradle installation to the container?
> or if gradle exists where it's directory?

In general, not. We use the Gradle Wrapper specifically because we don't want to bundle a specific version of Gradle and we want to allow the project the freedom to pick it.

You can build your image on top of this one and add Gradle if you wish.

> I am using this container to build cordova android app in bitbucket pipeline

This container is for building React Native apps, not Cordova apps
